// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtqa8qlw0-6Dr_yqLaNQa0PxM90_ReC4',
    appId: '1:926762026617:web:4817e0edcb513503c5b6a8',
    messagingSenderId: '926762026617',
    projectId: 'listadepets-gloriaporte',
    authDomain: 'listadepets-gloriaporte.firebaseapp.com',
    storageBucket: 'listadepets-gloriaporte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw19Gaafd_ZSrkfRmOp8lqWR3FBFhk3pc',
    appId: '1:926762026617:android:a4c3349995ca3c29c5b6a8',
    messagingSenderId: '926762026617',
    projectId: 'listadepets-gloriaporte',
    storageBucket: 'listadepets-gloriaporte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUIXZ2rJEvpKSLP2sCm8PsJPo2Dcitscc',
    appId: '1:926762026617:ios:f4cd63a835cda5f6c5b6a8',
    messagingSenderId: '926762026617',
    projectId: 'listadepets-gloriaporte',
    storageBucket: 'listadepets-gloriaporte.firebasestorage.app',
    iosBundleId: 'com.example.listaDePets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUIXZ2rJEvpKSLP2sCm8PsJPo2Dcitscc',
    appId: '1:926762026617:ios:f4cd63a835cda5f6c5b6a8',
    messagingSenderId: '926762026617',
    projectId: 'listadepets-gloriaporte',
    storageBucket: 'listadepets-gloriaporte.firebasestorage.app',
    iosBundleId: 'com.example.listaDePets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxtqa8qlw0-6Dr_yqLaNQa0PxM90_ReC4',
    appId: '1:926762026617:web:31c9763cbc16315bc5b6a8',
    messagingSenderId: '926762026617',
    projectId: 'listadepets-gloriaporte',
    authDomain: 'listadepets-gloriaporte.firebaseapp.com',
    storageBucket: 'listadepets-gloriaporte.firebasestorage.app',
  );

}